# Generated by Django 4.0.4 on 2022-05-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('cms_site', '0002_replace_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_1_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_1_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_2_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_2_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_body',
            field=models.TextField(blank=True, default='', verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_button_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name='Linked page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_button_text',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Button title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='overlay_title',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Title'),
        ),
    ]
