# Generated by Django 4.0.7 on 2022-08-09 11:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0003_designerspage_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='items_list',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Title')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('item_types', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Type of furniture', required=True, target_model='cms_site.CollectionItemType'))), ('finishings', wagtail.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Finishing', required=True, target_model='cms_site.CollectionItemFinishing'), required=False)), ('model', wagtail.snippets.blocks.SnippetChooserBlock(label='Model', required=True, target_model='cms_site.CollectionItemModel'))]))], use_json_field=True, verbose_name='Compositions, renders and photos'),
        ),
        migrations.AlterField(
            model_name='designerspage',
            name='designers_list',
            field=wagtail.fields.StreamField([('item', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock(label='Quote')), ('name', wagtail.blocks.CharBlock(label='Name')), ('role', wagtail.blocks.CharBlock(help_text="I.e.: 'Area collection designer'", label='Role')), ('description', wagtail.blocks.CharBlock(label='Description')), ('photo', wagtail.images.blocks.ImageChooserBlock(label='Photo'))]))], use_json_field=True, verbose_name='Compositions, renders and photos'),
        ),
    ]
