# Generated by Django 4.0.4 on 2022-05-16 16:07

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0003_remove_homepage_body_homepage_collection_1_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitemfinishing',
            options={'verbose_name': 'Collection item finishing', 'verbose_name_plural': 'Collection item finishings'},
        ),
        migrations.AlterModelOptions(
            name='collectionitemtype',
            options={'verbose_name': 'Collection item type', 'verbose_name_plural': 'Collection item types'},
        ),
        migrations.AddField(
            model_name='collection',
            name='items_list',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('item_type', wagtail.snippets.blocks.SnippetChooserBlock(required=True, target_model='cms_site.CollectionItemType'))]))], default=''),
            preserve_default=False,
        ),
    ]
