# Generated by Django 4.0.4 on 2022-05-17 09:19

from django.db import migrations, models
import django.db.models.deletion
import uuid
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('cms_site', '0004_alter_collectionitemfinishing_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='items_list',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('item_types', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Type of furniture', required=True, target_model='cms_site.CollectionItemType'))), ('finishings', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Finishing', required=True, target_model='cms_site.CollectionItemFinishing')))]))], verbose_name='Compositions, renders and photos'),
        ),
        migrations.CreateModel(
            name='CollectionItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale')),
            ],
            options={
                'verbose_name': 'Collection item model',
                'verbose_name_plural': 'Collection item model',
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
