# Generated by Django 4.0.7 on 2022-08-09 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('cms_site', '0004_alter_collection_items_list_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaIconsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, help_text='Facebook URL', null=True)),
                ('youtube', models.URLField(blank=True, help_text='Youtube URL', null=True)),
                ('instagram', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('vimeo', models.URLField(blank=True, help_text='Vimeo URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetailsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, default='info@moblesciurans.com', help_text='Direct e-mail', max_length=254, null=True)),
                ('address', models.URLField(blank=True, default='C/ Priora Xixilona, 14\n        08530 La Garriga\n        Barcelona', help_text='Telegram URL', null=True)),
                ('phone', models.URLField(blank=True, default='93 871 80 07', help_text='Whatsapp URL', null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
