# Generated by Django 4.1.7 on 2023-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cms_site",
            "0004_ajaxcontactsubmission_collection_customajaxcontact_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="description",
            field=models.TextField(blank=True, default="", verbose_name="Description"),
        ),
    ]
