# Generated by Django 4.0.4 on 2022-05-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0004_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionItemType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
            ],
        ),
    ]
