# Generated by Django 4.0.4 on 2022-05-17 15:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0005_alter_collection_items_list_collectionitemmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionitemmodel',
            options={'verbose_name': 'Collection item model', 'verbose_name_plural': 'Collection item models'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='items_list',
            field=wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(label='Title')), ('image', wagtail.images.blocks.ImageChooserBlock(label='Image')), ('item_types', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Type of furniture', required=True, target_model='cms_site.CollectionItemType'))), ('finishings', wagtail.core.blocks.ListBlock(wagtail.snippets.blocks.SnippetChooserBlock(label='Finishing', required=True, target_model='cms_site.CollectionItemFinishing'))), ('model', wagtail.snippets.blocks.SnippetChooserBlock(label='Model', required=True, target_model='cms_site.CollectionItemModel'))]))], verbose_name='Compositions, renders and photos'),
        ),
    ]
