# Generated by Django 4.1.7 on 2023-05-31 16:05

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("cms_site", "0005_aboutuspage_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutuspage",
            name="description",
            field=wagtail.fields.RichTextField(
                blank=True, default="", verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="aboutuspage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="finishings",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='L\'Acabat no és a la llista? Per afegir-ne més, ves a <a href="/cms/cms_site/collectionitemfinishing/" target="_blank">Acabats</a>.',
                related_name="finishings",
                to="cms_site.collectionitemfinishing",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="image",
            field=models.ForeignKey(
                help_text="To avoid cutting the picture in the thumbnail, the uploaded image should have a 1x1 proportion. Minimum recommended size is 2.000x2.000px.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="model",
            field=models.ForeignKey(
                help_text='El model no és a la llista? Per afegir-ne més, ves a <a href="/cms/cms_site/collectionitemmodel/" target="_blank">Models</a>.',
                on_delete=django.db.models.deletion.CASCADE,
                to="cms_site.collectionitemmodel",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="typologies",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='La Tipologia no és a la llista? Per afegir-ne més, ves a <a href="/cms/cms_site/collectionitemtype/" target="_blank">Tipologies</a>.',
                related_name="typologies",
                to="cms_site.collectionitemtype",
            ),
        ),
        migrations.AlterField(
            model_name="collectionspage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="customproject",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="customprojectspage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="designerspage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="legalpage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="newspage",
            name="header_image",
            field=models.ForeignKey(
                help_text="Aquesta imatge està pensada per ser decorativa i crear acompanyar el contingut. Segons la resolució i el dispositiu de l'usuari, la mida i proporció variarà, i per tant es retallaran parts de la imatge. La proporció recomanada és de 2x1, amb una mida mínima de 2.000x1.000px.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
    ]
