# Generated by Django 4.0.4 on 2022-05-17 15:02

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('cms_site', '0006_alter_collectionitemmodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('designers_list', wagtail.core.fields.StreamField([('item', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.CharBlock(label='Quote')), ('name', wagtail.core.blocks.CharBlock(label='Name')), ('title', wagtail.core.blocks.CharBlock(help_text="I.e.: 'Area collection designer'", label='Introduction title')), ('description', wagtail.core.blocks.CharBlock(label='Description')), ('photo', wagtail.images.blocks.ImageChooserBlock(label='Photo'))]))], verbose_name='Compositions, renders and photos')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
