# Generated by Django 4.0.7 on 2022-08-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('cms_site', '0007_alter_contactdetailssettings_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='collection_3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_3_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='collection_3_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_projects_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_projects_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AddField(
            model_name='homepage',
            name='custom_projects_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='display_header_highlight',
            field=models.BooleanField(default=True, verbose_name='Display header highlighted overlay'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='display_instagram_feed',
            field=models.BooleanField(default=True, verbose_name='Display Instagram feed section'),
        ),
    ]
