# Generated by Django 4.1.7 on 2023-06-08 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
        ("cms_site", "0008_remove_collectionspage_header_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homepage",
            name="collection_1_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="collection_1_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Collection's page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="collection_2_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="collection_2_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Collection's page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="collection_3_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="collection_3_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Collection's page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="custom_projects_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="custom_projects_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Custom projects' page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="overlay_button_page",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
                verbose_name="Linked page",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="overlay_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image",
            ),
        ),
    ]
