# Generated by Django 4.1.7 on 2023-06-09 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0009_alter_homepage_collection_1_image_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionitemfinishing",
            old_name="title",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="collectionitemtype",
            old_name="title",
            new_name="name",
        ),
    ]
