# Generated by Django 4.1.7 on 2023-06-12 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0010_rename_title_collectionitemfinishing_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionitem",
            old_name="title",
            new_name="title_ca",
        ),
    ]
