# Generated by Django 4.0.7 on 2022-08-11 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('cms_site', '0010_homepage_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designerspage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
    ]
