# Generated by Django 4.0.7 on 2022-08-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_site', '0012_collectionspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionspage',
            name='menu_label',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Títol al menú'),
        ),
    ]
