# Generated by Django 4.0.7 on 2022-09-13 09:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('cms_site', '0013_collectionspage_menu_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProject',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('images', wagtail.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock())], use_json_field=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CustomProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('menu_label', models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='collectionspage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
    ]
