# Generated by Django 4.0.7 on 2022-09-20 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('cms_site', '0013_collectionspage_menu_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AddField(
            model_name='collectionspage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='collectionspage',
            name='menu_label',
            field=models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title'),
        ),
        migrations.AlterField(
            model_name='designerspage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.CreateModel(
            name='CustomProjectsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('menu_label', models.CharField(blank=True, help_text='If not set, the menu title will be the page title.', max_length=15, null=True, verbose_name='Menu title')),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='CustomProject',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('header_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image')),
                ('images_collection', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.collection')),
                ('main_section_image', models.ForeignKey(help_text='This image will be used in the Custom Projects section, when displaying the list of projects.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Main section image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
