# Generated by Django 4.1.1 on 2022-09-23 12:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtailcore", "0076_modellogentry_revision"),
        (
            "cms_site",
            "0014_collection_header_image_collectionspage_header_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=80, verbose_name="Title")),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Image",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        help_text='The model is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemmodel/" target="_blank">Snippets</a>.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_site.collectionitemmodel",
                        verbose_name="Model",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="collection",
            name="items_list",
        ),
        migrations.AlterField(
            model_name="collection",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="collectionspage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="customproject",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="customproject",
            name="images_collection",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="wagtailcore.collection",
            ),
        ),
        migrations.AlterField(
            model_name="customproject",
            name="main_section_image",
            field=models.ForeignKey(
                help_text="This image will be used in the Custom Projects section, when displaying the list of projects.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Main section image",
            ),
        ),
        migrations.AlterField(
            model_name="customprojectspage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="designerspage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
        migrations.CreateModel(
            name="ItemTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        help_text='The type is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemtype/" target="_blank">Snippets</a>.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_site.collectionitemtype",
                        verbose_name="Type",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="types",
                        to="cms_site.collectionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ItemFinishings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "finishing",
                    models.ForeignKey(
                        help_text='The finishing is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemfinishing/" target="_blank">Snippets</a>.',
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cms_site.collectionitemfinishing",
                        verbose_name="Finishing",
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finishings",
                        to="cms_site.collectionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="collection_items",
                to="cms_site.collection",
            ),
        ),
    ]
