# Generated by Django 4.1.1 on 2022-09-28 09:21

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0015_collectionitem_remove_collection_items_list_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectionitem",
            name="finishings",
            field=modelcluster.fields.ParentalManyToManyField(
                related_name="finishings", to="cms_site.collectionitemfinishing"
            ),
        ),
        migrations.DeleteModel(
            name="ItemFinishings",
        ),
    ]
