# Generated by Django 4.0.7 on 2022-09-13 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('cms_site', '0015_collection_header_image_collectionspage_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproject',
            name='main_section_image',
            field=models.ForeignKey(default='', help_text='This image will be used in the Custom Projects section, when displaying the list of projects.', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Main section image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collection',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='collectionspage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='customproject',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='customprojectspage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image', verbose_name='Header image'),
        ),
    ]
