# Generated by Django 4.1.1 on 2022-09-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0016_collectionitem_finishings_delete_itemfinishings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionitemfinishing",
            old_name="name",
            new_name="title",
        ),
    ]
