# Generated by Django 4.1.1 on 2022-09-28 09:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0017_rename_name_collectionitemfinishing_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="collectionitemtype",
            old_name="name",
            new_name="title",
        ),
        migrations.AddField(
            model_name="collectionitem",
            name="typologies",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='The type is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemtype/" target="_blank">Typologies</a>.',
                related_name="typologies",
                to="cms_site.collectionitemtype",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="finishings",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='The finishing is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemfinishing/" target="_blank">Finishings</a>.',
                related_name="finishings",
                to="cms_site.collectionitemfinishing",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="model",
            field=models.ForeignKey(
                help_text='The model is not in the list? To add more, go to <a href="/cms/snippets/cms_site/collectionitemmodel/" target="_blank">Models</a>.',
                on_delete=django.db.models.deletion.CASCADE,
                to="cms_site.collectionitemmodel",
                verbose_name="Model",
            ),
        ),
        migrations.DeleteModel(
            name="ItemTypes",
        ),
    ]
