# Generated by Django 4.1.1 on 2023-02-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_ajax_contact_form", "0003_auto_20210204_1616"),
        ("cms_site", "0022_customprojectspage_introduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomAjaxContact",
            fields=[
                (
                    "ajaxcontactpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtail_ajax_contact_form.ajaxcontactpage",
                    ),
                ),
                (
                    "menu_label",
                    models.CharField(
                        blank=True,
                        help_text="If not set, the menu title will be the page title.",
                        max_length=15,
                        null=True,
                        verbose_name="Menu title",
                    ),
                ),
                (
                    "subject_label",
                    models.CharField(
                        default="Subject",
                        help_text="Label for the Subject field.",
                        max_length=250,
                        verbose_name="subject",
                    ),
                ),
                (
                    "phone_label",
                    models.CharField(
                        default="Phone",
                        help_text="Label for the Phone field.",
                        max_length=250,
                        verbose_name="phone",
                    ),
                ),
                (
                    "profile_label",
                    models.CharField(
                        default="Profile",
                        help_text="Label for the Profile field.",
                        max_length=250,
                        verbose_name="profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact page",
            },
            bases=("wagtail_ajax_contact_form.ajaxcontactpage", models.Model),
        ),
    ]
