# Generated by Django 4.1.1 on 2023-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0023_customajaxcontact"),
    ]

    operations = [
        migrations.AddField(
            model_name="customajaxcontact",
            name="personal_data_auth_label",
            field=models.CharField(
                default="Treatment of personal data authorization",
                help_text="Label for the Personal data treatment checkbox.",
                max_length=250,
                verbose_name="personal data treatment",
            ),
        ),
        migrations.AddField(
            model_name="customajaxcontact",
            name="personal_data_comercial_auth_label",
            field=models.CharField(
                default="Treatment of personal data authorization for comercial purposes",
                help_text="Label for the Personal data for comercial use treatment checkbox.",
                max_length=250,
                verbose_name="personal data for comercial use treatment",
            ),
        ),
    ]
