# Generated by Django 4.1.1 on 2023-02-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtail_ajax_contact_form", "0004_ajaxcontactpage_header_image"),
        ("cms_site", "0024_customajaxcontact_personal_data_auth_label_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AjaxContactSubmission",
            fields=[
                (
                    "contactsubmission_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtail_ajax_contact_form.contactsubmission",
                    ),
                ),
                ("subject", models.CharField(max_length=120, verbose_name="subject")),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="phone"
                    ),
                ),
                (
                    "profile",
                    models.CharField(
                        blank=True, default="", max_length=120, verbose_name="profile"
                    ),
                ),
                (
                    "personal_data_auth",
                    models.BooleanField(
                        verbose_name="Treatment of personal data authorization"
                    ),
                ),
                (
                    "personal_data_comercial_auth",
                    models.BooleanField(
                        verbose_name="Treatment of personal data authorization for comercial purposes"
                    ),
                ),
            ],
            bases=("wagtail_ajax_contact_form.contactsubmission",),
        ),
    ]
