# Generated by Django 4.1.1 on 2023-02-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0025_ajaxcontactsubmission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ajaxcontactsubmission",
            name="subject",
            field=models.CharField(
                blank=True, default="", max_length=120, verbose_name="subject"
            ),
        ),
        migrations.DeleteModel(
            name="ContactPage",
        ),
    ]
