# Generated by Django 4.1.1 on 2023-02-22 11:08

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0026_alter_ajaxcontactsubmission_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="history_items_list",
            field=wagtail.fields.StreamField(
                [
                    (
                        "item",
                        wagtail.blocks.StructBlock(
                            [
                                ("year", wagtail.blocks.IntegerBlock(label="Year")),
                                ("title", wagtail.blocks.CharBlock(label="Títol")),
                                ("text", wagtail.blocks.TextBlock(label="Text")),
                                (
                                    "photo",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Photo"
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="History points",
            ),
        ),
    ]
