# Generated by Django 4.1.1 on 2023-02-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0027_aboutuspage_history_items_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_1",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 1 description"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_2",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 2 description"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_3",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 3 description"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_4",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 4 description"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_5",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 5 description"
            ),
        ),
        migrations.AddField(
            model_name="aboutuspage",
            name="video_description_6",
            field=models.TextField(
                blank=True, default="", verbose_name="Video 6 description"
            ),
        ),
    ]
