# Generated by Django 4.1.1 on 2023-02-22 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0031_historyitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuspage",
            name="history_items_list",
        ),
    ]
