# Generated by Django 4.1.7 on 2023-03-01 15:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("cms_site", "0033_instagrampost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectionitem",
            name="finishings",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='The finishing is not in the list? To add more, go to <a href="/cms/cms_site/collectionitemfinishing/" target="_blank">Finishings</a>.',
                related_name="finishings",
                to="cms_site.collectionitemfinishing",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="model",
            field=models.ForeignKey(
                help_text='The model is not in the list? To add more, go to <a href="/cms/cms_site/collectionitemmodel/" target="_blank">Models</a>.',
                on_delete=django.db.models.deletion.CASCADE,
                to="cms_site.collectionitemmodel",
                verbose_name="Model",
            ),
        ),
        migrations.AlterField(
            model_name="collectionitem",
            name="typologies",
            field=modelcluster.fields.ParentalManyToManyField(
                help_text='The type is not in the list? To add more, go to <a href="/cms/cms_site/collectionitemtype/" target="_blank">Typologies</a>.',
                related_name="typologies",
                to="cms_site.collectionitemtype",
            ),
        ),
    ]
