version: "3.5"

networks:
  develop_wagtail_boilerplate_network:
    name: develop_wagtail_boilerplate_network

services:
  develop_wagtail_boilerplate_app:
    restart: on-failure
    container_name: develop_wagtail_boilerplate_app
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/development.env
    command: gunicorn conf.wsgi:application --bind 0.0.0.0:80 --reload --threads=10
    volumes:
      - ../src:/srv
    depends_on:
      - develop_wagtail_boilerplate_db
    networks:
      - develop_wagtail_boilerplate_network
    ports:
      - 80:80

  develop_wagtail_startup_commands:
    restart: on-failure
    container_name: develop_wagtail_startup_commands
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      target: development
    env_file: ./settings/development.env
    command: python manage.py migrate
    volumes:
      - ../src:/srv
    depends_on:
      -   develop_wagtail_boilerplate_app
    networks:
      - develop_wagtail_boilerplate_network

  develop_wagtail_boilerplate_db:
    container_name: develop_wagtail_boilerplate_db
    image: postgres:14
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ../dumps:/dumps
    networks:
      - develop_wagtail_boilerplate_network
