# Generated by Django 4.1.7 on 2023-03-02 10:57

from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("wagtailcore", "0083_workflowcontenttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=120, verbose_name="name")),
                ("email", models.EmailField(max_length=255, verbose_name="e-mail")),
                ("message", models.TextField(verbose_name="message")),
            ],
            options={
                "verbose_name": "contact form submission",
                "verbose_name_plural": "contact form submissions",
            },
        ),
        migrations.CreateModel(
            name="AjaxContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "name_label",
                    models.CharField(
                        default="Your name",
                        help_text="Label for the Name field.",
                        max_length=250,
                        verbose_name="name",
                    ),
                ),
                (
                    "email_label",
                    models.CharField(
                        default="Your e-mail",
                        help_text="Label for the e-mail field.",
                        max_length=250,
                        verbose_name="email",
                    ),
                ),
                (
                    "message_label",
                    models.CharField(
                        default="Message",
                        help_text="Label for the Message field.",
                        max_length=250,
                        verbose_name="message",
                    ),
                ),
                (
                    "success_msg",
                    wagtail.fields.RichTextField(
                        default="Message sent, thanks for contacting us!",
                        verbose_name="success message",
                    ),
                ),
                (
                    "to_address",
                    models.EmailField(
                        blank=True,
                        help_text="E-mail to notify when a new submission is received. Leave it empty to disable the notifications.",
                        max_length=254,
                        null=True,
                        verbose_name="to address",
                    ),
                ),
                (
                    "notification_subject",
                    models.CharField(
                        blank=True,
                        help_text="If empty, you will not get e-mail notifications for new form submissions.",
                        max_length=250,
                        null=True,
                        verbose_name="subject",
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Header image",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
