# Generated by Django 3.1.5 on 2021-02-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_ajax_contact_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxcontactpage',
            name='success_msg',
            field=models.TextField(default='Message sent, thanks for contacting us!', verbose_name='success message'),
        ),
    ]
