# Generated by Django 3.1.5 on 2021-02-04 15:16

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_ajax_contact_form', '0002_auto_20210204_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajaxcontactpage',
            name='success_msg',
            field=wagtail.fields.RichTextField(default='Message sent, thanks for contacting us!', verbose_name='success message'),
        ),
    ]
