# Generated by Django 4.1.1 on 2023-02-20 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("wagtail_ajax_contact_form", "0003_auto_20210204_1616"),
    ]

    operations = [
        migrations.AddField(
            model_name="ajaxcontactpage",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Header image",
            ),
        ),
    ]
