# Generated by Django 4.0.4 on 2022-05-16 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examplespage',
            name='body',
        ),
    ]
