# Generated by Django 4.0.4 on 2022-05-16 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
        ('examples', '0003_examplespage_collection_1_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplespage',
            name='collection_1_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AddField(
            model_name='examplespage',
            name='collection_2_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.page', verbose_name="Collection's page"),
        ),
        migrations.AlterField(
            model_name='examplespage',
            name='collection_1_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='examplespage',
            name='collection_2_title',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Title'),
        ),
    ]
