# Generated by Django 4.0.4 on 2022-05-16 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'verbose_name': 'Blog category', 'verbose_name_plural': 'Blog categories'},
        ),
    ]
