# Generated by Django 4.0.4 on 2022-04-21 14:57

from django.db import migrations


def replace_home(apps, schema_editor):
    """
    If we were using a standalone Wagtail installation, we would already have
    a 'home' app with a 'HomePage' page model and we could just extend it,
    and no extra steps would be needed in the CMS admin.
    But having Wagtail installed on top of an existing Django installation
    leaves us without this initial 'home' app, but Wagtail needs to create
    a page instance initially anyway (I guess that if there's only the Root
    level something might crash?).

    That means that when you access the root level of your site, aka:
    https://localhost:8001/
    You will always see the Welcome page and you cannot modify its model
    anywhere.
    From that point you normally need to:
    - Create an app with some model that you will use as the home page.
    - After migrating, access the admin panel and create a page at root leve
      using your new model (with a slug different than 'home').
    - Go to Sites and modify the default site to make the new page the default
      one.
    - Delete the Welcome page.
    - Edit your new page and (now that the slug is available) replace its slug
      with 'home'. You'll see that this slug is somehow hardcoded to make it
      answer to https://localhost:8001/, not to https://localhost:8001/home/.

    Our experience is that while developing a new project, each time you reset
    the database you then need to repeat these steps in the admin panel which
    is very annoying.

    The purpose of this migration is to replace the "Welcome to Wagtail" page
    by our own Home page automatically so none of these steps are necessary
    anymore.

    - The Root page in Wagtail 2.16.2:
    root_page_fields = {
        'id': 1,
        'path': '0001',
        'depth': 1,
        'numchild': 1,
        'translation_key': UUID('f3a676c1-a472-4d02-8d8d-25ba7aa263e4'),
        'locale_id': 1,
        'title': 'Root',
        'draft_title': 'Root',
        'slug': 'root',
        'content_type_id': 1,
        'live': True,
        'has_unpublished_changes': False,
        'url_path': '/',
        'owner_id': None,
        'seo_title': '',
        'show_in_menus': False,
        'search_description': '',
        'go_live_at': None,
        'expire_at': None,
        'expired': False,
        'locked': False,
        'locked_at': None,
        'locked_by_id': None,
        'first_published_at': None,
        'last_published_at': None,
        'latest_revision_created_at': None,
        'live_revision_id': None,
        'alias_of_id': None,
    }

    - The "Welcome to Wagtail" default Home Page in Wagtail 2.16.2:
    welcome_to_wagtail_page_fields = {
        'id': 2,
        'path': '00010001',
        'depth': 2,
        'numchild': 0,
        'translation_key': UUID('f31ea051-eeac-43b1-bc51-d132e70b74bb'),
        'locale_id': 1,
        'title': 'Welcome to your new Wagtail site!',
        'draft_title': 'Welcome to your new Wagtail site!',
        'slug': 'home',
        'content_type_id': 1,
        'live': True,
        'has_unpublished_changes': False,
        'url_path': '/home/',
        'owner_id': None,
        'seo_title': '',
        'show_in_menus': False,
        'search_description': '',
        'go_live_at': None,
        'expire_at': None,
        'expired': False,
        'locked': False,
        'locked_at': None,
        'locked_by_id': None,
        'first_published_at': None,
        'last_published_at': None,
        'latest_revision_created_at': None,
        'live_revision_id': None,
        'alias_of_id': None
    }
    """
    home_page_model = apps.get_model("home", "HomePage")
    site_model = apps.get_model("wagtailcore", "Site")
    page_model = apps.get_model("wagtailcore", "Page")

    print(home_page_model.objects.all())
    fields = {
        'path': '00010002',
        'depth': 2,
        # 'numchild': 0,
        'locale_id': 1,
        'title': 'Default home',
        # 'draft_title': 'Default home',
        'slug': 'temporary-slug',
        'content_type_id': 38,
        'live': True,
        # 'has_unpublished_changes': False,
        # 'url_path': '/default-home/',
        # 'owner_id': 1,
        # 'seo_title': '',
        # 'show_in_menus': False,
        'search_description': '',
        # 'live_revision_id': 1,
        # 'page_ptr_id': 5,
        'body': '<p>Default home</p>'
    }
    new_home = home_page_model(**fields)
    new_home.save()

    print(site_model.objects.all())
    initial_site = site_model.objects.all()[0]
    initial_site.root_page = new_home
    initial_site.save()

    new_home.slug = "home"
    new_home.save()
    print("Home page replaced.")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('wagtailcore', '__latest__'),
    ]

    operations = [
        # migrations.RunPython(replace_home),
    ]
